# Generated by Django 4.2.5 on 2023-09-17 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Checkout',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=150, null=True)),
                ('name', models.CharField(default='', max_length=150)),
                ('product', models.CharField(max_length=150)),
                ('price', models.IntegerField()),
                ('Situation', models.CharField(choices=[('Approved', 'Approved'), ('Shipped', 'Shipped'), ('Delivered', 'Delivered')], default='Approved', max_length=50, null=True)),
                ('place', models.CharField(default='', max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='items',
            name='quan',
        ),
    ]
