# Generated by Django 4.2.5 on 2023-09-17 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0002_checkout_remove_items_quan'),
    ]

    operations = [
        migrations.AddField(
            model_name='items',
            name='quan',
            field=models.IntegerField(default=10),
            preserve_default=False,
        ),
    ]
