# Generated by Django 4.2.5 on 2023-09-17 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0004_cartitem_delete_checkout_remove_items_cart_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Address', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=200)),
                ('price', models.IntegerField(max_length=200)),
                ('Status', models.CharField(choices=[('Approved', 'Approved'), ('Shipped', 'Shipped'), ('Delivered', 'Delivered')], default='Pending', max_length=50, null=True)),
            ],
        ),
    ]
