# Generated by Django 4.2.5 on 2023-09-17 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0005_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='Address',
            field=models.CharField(max_length=200),
        ),
    ]
