# Generated by Django 4.2.5 on 2023-09-17 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0002_product_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='quan',
            field=models.IntegerField(null=True),
        ),
    ]
